### ISSUE TITLE
filename.match(/#\d+-(.*)/)[0]; Cannot read property '0' of null

### ISSUE THREAD

**Issue by vibha-somashekhara** [reportportal/agent-js-cypress#10]
I following the instructions as in readme file.  

1) installed both dependencies
2) Added reportportal options in cypress.json
{
  "defaultCommandTimeout": 10000,
  "env": {
    "baseURL": "my url"
  },
  "projectId": "pyvpcd",

    "reporter": "agent-js-cypress/rp-reporter.js",
    "reporterOptions": {
        "endpoint":"https://web.demo.reportportal.io",
        "token":"d1726dd7-5dc8-4cf2-82e7-e08aee5acf67",
        "launch":"default_TEST_EXAMPLE",
        "project":"default_personal",
        "description":"PROJECT_DESCRIPTION",
        "isLaunchMergeRequired":true
    }
}

3) Added cypress.js under scripts and copied the code (I haven't made any changes to code)

4) Added a script in package.json.
    "cypress": "node scripts/cypress.js"

When I run tests, I get below error from report portal agent:

/Cypress/node_modules/reportportal-client/lib/helpers.js:9
    const launchNumberAndId = filename.match(/#\d+-(.*)/)[0];
                                                         ^
TypeError: Cannot read property '0' of null
    at getIdFormFileName (Cypress/node_modules/reportportal-client/lib/helpers.js:9:58)
    at Array.map (<anonymous>)
    at Object.readLaunchesFromFile (/Cypress/node_modules/reportportal-client/lib/helpers.js:35:27)

My questions are:
1) Why is "isLaunchMergeRequired" set to true in cypress.json? - If I set to false, no error is thrown. However, nothing is logged in ReportPortal.
2) The code you have provided to add in cypress.js - It only executes mergeLaunches code..? I cannot see anything for creating launch. Is there anything that I need to change?
3) Do you have an example of cypress and reportPortal integration?
4) How can I resolve my issue?

Thanks,
Vibha

**Comment by evjlobanova** [comment]
@AmsterGet Could you please help with this?

**Comment by vibha-somashekhara** [comment]
I tried this again by not adding cypress.js at all. I could get the results on ReportPortal. But each spec is logged as a separate launch.

**Comment by wiibaker** [comment]
I second @vibha-somashekhara on the question

> Do you have an example of cypress and reportPortal integration?

Would like to also see an working example project with correct configuration and _clearly_ stated the commands that are needed to run. Now I'm a bit confused would you need to run the tests by `cypress run` or with the `node scripts/cypress.js` ??

**Comment by ElenaRomanchuk** [comment]
Hi!
We have just released the new version of cypress reporter as a new package @reportportal/agent-js-cypress: https://www.npmjs.com/package/@reportportal/agent-js-cypress. It has a new possibility of runtime merge launch into single: https://github.com/reportportal/agent-js-cypress#automatically-merge-launches. You can try it now.
Please, let us know if this solves your issue.
Also you can find the example of usage `agent-js-cypress` here: https://github.com/reportportal/examples-js/tree/master/example-cypress.

**Comment by evjlobanova** [comment]
Closed due to no answer
