### ISSUE TITLE
Possible to add launchAttributes ?

### ISSUE THREAD

**Issue by cwolf24** [reportportal/agent-js-cypress#106]
I tried to add some Launch attributes in the same way, we do it with the [agent-js-codecept](https://github.com/reportportal/agent-js-codecept), but the attributes are not available in reportportal.

Can i somehow add Launchattributes?

This is how we do it with the codecept agent ✅ :
```
reportportal: {
...
launchAttributes: [
        {
          key: 'Author',
          value: process.env.GITHUB_ACTOR || 'Local Launch'
        },
        {
          key: 'Branch',
          value: process.env.GITHUB_HEAD_REF || process.env.GITHUB_REF_NAME || 'Local Launch'
        },
        {
          key: 'PR',
          value: process.env.PR_ID || 'Local Launch'
        }]
}
```

With the cypress agent i tried 🔴 :
```
config.reporterOptions.launchAttributes = [
      {
        key: "Author",
        value: process.env.GITHUB_ACTOR || "Local Launch"
      },
      {
        key: "Branch",
        value:
          process.env.GITHUB_HEAD_REF ||
          process.env.GITHUB_REF_NAME ||
          "Local Launch"
      },
      {
        key: "PR",
        value: process.env.PR_ID || "Local Launch"
      }
    ];
```

**Comment by ekorneeva24** [comment]
@cwolf24 maybe the key is called differently in the agent.
This is what ReportPortal awaits https://github.com/reportportal/client-javascript#startlaunch
Maybe you will be able to find how agent-js-cypress renames this key in the source code of the agent.

**Comment by AmsterGet** [comment]
Hello @cwolf24 !
You can just add an `attributes` field to reporter options.
https://github.com/reportportal/examples-js/blob/master/example-cypress/cypress.json#L21
I'll update the readme file to mention this field.

**Comment by cwolf24** [comment]
@AmsterGet Thanks, with `attributes` it works now. 👍

**Comment by Zenin-Dmitry** [comment]
Hi,
When calling tests, I want to set special attributes that have a key and a value, and not just a value. I've tried different forms of notation, but at best only the value is passed. I need this to use filters by attribute values. I studied all the documentation, but I still couldn’t pass an array with attributes to the reportport. Please tell me the correct form. 
If you pass attributes like this, they work, but I just need the key and value.
`--reporter-options description=Shema,attributes=[attr1,attr2,arrt3]`
I've tried many options, some give an error, some just don't transfer.
`--reporter-options description=Shema,attributes=["key12:SLID"]`
`--reporter-options description=Shema,attributes=[{"key12:SLID"}]`
`--reporter-options description=Shema,attributes=[{"key12":"SLID"}]`
what is the correct option?
