### ISSUE TITLE
Not working with "yarn" package manager

### ISSUE THREAD

**Issue by kaliahinartem** [reportportal/agent-js-cypress#109]
Hello! 

My project uses yarn as a package manager.
Basically I was trying to integrate cypress-agent with my cypress config, but have been struggling a lot with making it work.

As far as I understood, the problem was that node-ipc for some reason wouldn't connect and I'm getting connection errors:
![image](https://user-images.githubusercontent.com/42048389/154092298-d1217199-dfe4-4432-8aff-25ae9feab584.png)

Eventually I went to examples repo (https://github.com/reportportal/examples-js) and tried to test it from there, but (to my surprise) it also didn't work with "yarn".

Then I installed it through npm and everything worked as expected. There was no error and portal has started receiving messages from my tests.

So please if you are aware of this issue - let me know if it's fixable, otherwise for us it's not possible to use reports dashboard.

Steps to reproduce:
- Clone examples repository (https://github.com/reportportal/examples-js)
- run "yarn install"
- update cypress.json to have correct values (token, endpoint, etc)
- Go to "node_modules/@reportportal/agent-js-cypress/lib/plugin/ipcClient.js and comment line 29 (this will allow to see node-ipc logs in your console)
- run "yarn test"

In the console you will se the same log that I attached above.

When install is done via "npm install" everything works.

Please let me know if this is enough information, thanks!

Thanks a lot in advance.

**Comment by jonasleao** [comment]
I have the same problem some help pls

**Comment by rajaspar** [comment]
Are there any plans to support this?
