### ISSUE TITLE
Unintended behavior of blobbing in get*Screenshot methods causes screenshots not to be found. 

### ISSUE THREAD

**Issue by rdyercrx** [reportportal/agent-js-cypress#114]
Y'all are gonna need to rethink the patterning with the getFailed|passed|CustomScreenshots methods 

We've got suite scopes demarcated by [suite] in the test name in addition to splitting out by describe blocks.  glob tends to cause some major issues with the way you guys do 

```
const pattern = `**/*${testTitle.replace(/[",',:]/g, '')} (failed).png`
glob.sync(pattern);
```
 will return empty for us with our filenames of pattern
 [smoke] <describe text> -- [smoke] <it text> (failed).png
 , but only when you combine the ${} interp with the globbing in the same operation.
 I'd recommend going with a two stage filter.
 
 ```
 pattern1 = `**/* (failed).png`
 pattern2 = `${testTitle}`
 glob.sync(pattern1).filter(it => it.include(pattern2))
 ```
 Where the glob.sync(pattern1) gets you all the failed, then the filter picks out the one that includes the test name, then hope someone isn't clever and names the describe block the same thing as the it block.  
 Really not sure why the globbing doesn't like it, and just had to toy with the Node REPL for a while to home in on it, but that's causing us to not get our screenshots into reportportal. 
 
 It's an artifact of a test grouping initiative forever ago, so it's not that for us to clear that out of our test repository in it's entirety, but if it comes to that, it just may be what we have to do.
 

![Screen Shot 2022-04-15 at 10 36 53 PM](https://user-images.githubusercontent.com/63601113/163660058-5431821c-dcfa-4c07-8859-65ac91a698f4.png)

 Lemme know if you need more info.  
![Screen Shot 2022-04-15 at 10 44 42 PM](https://user-images.githubusercontent.com/63601113/163660268-dcab4f65-0b38-452a-92d8-78643d6c1139.png)

**Comment by AmsterGet** [comment]
Hello @rdyercrx !
The screenshot mechanism has been completely rewritten and released in version [5.1.2](https://github.com/reportportal/agent-js-cypress/releases/tag/v5.1.2).
Have you tried using it?
Please check your issue with the latest agent version.
Looking forward to your feedback!

**Comment by AmsterGet** [comment]
I'm going to close this issue.
Feel free to reopen it if your request is still relevant.

**Comment by AmsterGet** [comment]
Related issues:
https://github.com/reportportal/agent-js-cypress/issues/73
https://github.com/reportportal/agent-js-cypress/issues/78
https://github.com/reportportal/agent-js-cypress/issues/68
https://github.com/reportportal/agent-js-cypress/issues/71
