### ISSUE TITLE
Request failed with status code 405

### ISSUE THREAD

**Issue by donrifad** [reportportal/agent-js-cypress#138]
<img width="419" alt="Screen Shot 2022-12-16 at 10 49 40 AM" src="https://user-images.githubusercontent.com/5151534/208039622-89628580-4a77-442f-b02d-3c52a72be9f6.png">
`Error: Request failed with status code 405
    at /Users//node_modules/@reportportal/client-javascript/lib/rest.js:37:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Fail to finish test Error: Request failed with status code 405
    at /Users/node_modules/@reportportal/client-javascript/lib/rest.js:37:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

How to solve this issue ?

**Comment by DzmitryHumianiuk** [comment]
@AmsterGet any ideas?

**Comment by DzmitryHumianiuk** [comment]
@donrifad what are the version of the agent and which agent are you using?

405 error code means that the server knows the request method, but the target resource doesn't support this method.
which makes me think, that the library just outdated.

**Comment by AmsterGet** [comment]
Hello @donrifad !
The issue looks similar to https://github.com/reportportal/agent-js-playwright/issues/75.
Could you please recheck it with suggested solution?

**Comment by donrifad** [comment]
Thanks, guys for the prompt reply, I was able to solve this, I was using the wrong endpoint 
I had to use the endpoint as <https://demoreportportal.io/api/v1>.

Directly copying the endpoint from rp did not work.

**Comment by AmsterGet** [comment]
Ok, so I'll close the issue!
Feel free to open another one in case of any questions.
