### ISSUE TITLE
[help]: Cypress reports uploading to Report portal does not have screenshots/videos on failure

### ISSUE THREAD

**Issue by toshikagarwal** [reportportal/agent-js-cypress#139]
Cypress reports uploading to Report portal does not have screenshots/videos on failure

We trigger our tests on Cypress framework, the test failures do not automatically capture the screenshots when uploaded to Report portal, is there some way to configure this?

**Comment by codeyoli** [comment]
Any updates on this?

**Comment by mbryl6** [comment]
Hello @toshikagarwal ,
Could you please show us your RP config? Here's the information on how to find it: https://github.com/reportportal/agent-js-cypress?tab=readme-ov-file#cypressconfigjs

**Comment by AmsterGet** [comment]
Progress on this issue can be followed in a similar thread - https://github.com/reportportal/agent-js-cypress/issues/160
