### ISSUE TITLE
Is it possible to incorporate this plugin while executions done from cypress open? 

### ISSUE THREAD

**Issue by NSnietol** [reportportal/agent-js-cypress#166]
Hi dear team, 

I have a project set up with the agent and works smoothly as long as I call my tests from the console using the parameters to the config file where I set up the report portal, however, if I run the cypress open command and then execute any script even when I call cypress open --config-file with the example file the results are not being aggregated.

Example cypress.config.ts

```const { defineConfig } = require('cypress');
const registerReportPortalPlugin = require('@reportportal/agent-js-cypress/lib/plugin');

module.exports = defineConfig({
  reporter: '@reportportal/agent-js-cypress',
  reporterOptions: {
    endpoint: '',
    token: '',
    launch: 'Smoke',
    project: 'REPORT-PORTAL-CYPRESS',
    description: 'asserting that the most crucial functions of a program work',
    attributes: [
      {
        key: 'ENV',
        value: 'PRODUCTION',
      }
    ],
  },
  e2e: {
    setupNodeEvents(on: any, config: any) {
      return registerReportPortalPlugin(on, config);
    },
    specPattern: 'cypress/e2e/*.js',

  },
});
```

**Comment by AmsterGet** [comment]
Hello @NSnietol !
It is a Cypress restriction not to execute any reporters when running tests through the GUI.
Closed [Cypress repo request](https://github.com/cypress-io/cypress-documentation/issues/5423) and mention in their documentation that [The reporter used during **cypress run**](https://docs.cypress.io/guides/references/configuration#:~:text=redirect%20before%20erroring.-,reporter,-spec)
