### ISSUE TITLE
Automatically merge launches custom script is not working 

### ISSUE THREAD

**Issue by e-fedosser** [reportportal/agent-js-cypress#167]
Hello @AmsterGet ,
When I try to run [this](https://github.com/reportportal/agent-js-cypress#automatically-merge-launches) custom script by using this command: **node scripts/cypress.js** then I'm getting an error as below:
![image](https://user-images.githubusercontent.com/91736304/230381603-c8b44131-1757-41ca-916b-c8a17e963127.png)
Any idea what's is wrong here?

**Comment by AmsterGet** [comment]
Hello @e-fedosser !
Did you mean [this part](https://github.com/reportportal/agent-js-cypress#add-file-to-run-cypress-with-custom-behavior) in the docs?
Anyway, seems like your setup requires to provide `remote-debugging-port` option for electron.
Did you provide it while running the tests via CLI?

**Comment by e-fedosser** [comment]
Yes this part. 
Yes I use this tag
![image](https://user-images.githubusercontent.com/91736304/230386832-f181bad5-c8ff-4d3b-9bd7-4c9f2484ff0a.png)
****

**Comment by e-fedosser** [comment]
as a result Im getting this error:
![image](https://user-images.githubusercontent.com/91736304/230387052-234b315a-1ebc-4503-9c19-cafb17463ec5.png)

**Comment by AmsterGet** [comment]
@e-fedosser as I see you use the `@NeuraLegion/cypress-har-generator` package.
And the missed option required by it, please refer their [docs](https://github.com/NeuraLegion/cypress-har-generator#generating-a-har-file) for details.
They are also referring the official [Electron documentation](https://www.electronjs.org/docs/latest/api/command-line-switches#--remote-debugging-portport) for more information. Possibly, you can set it via ENV variables.

![image](https://user-images.githubusercontent.com/31861805/230390189-eb572174-f83e-4bd2-ac4a-cbe1d2d53164.png)

**Comment by e-fedosser** [comment]
Yep, probably it's somehow related issue :) 
Thanks @AmsterGet  👍

**Comment by e-fedosser** [comment]
So my problem is resolved when I enabled autoMerge but it's generate new problem where my lunches are not stopped at all.
Any thoughts how to fix it @AmsterGet ? :)
![image](https://user-images.githubusercontent.com/91736304/233105506-a79f7c68-693d-4d55-9ee6-f4663dc3f800.png)

**Comment by AmsterGet** [comment]
Hi @e-fedosser !
Please try the workarounds described [here](https://github.com/reportportal/agent-js-cypress/issues/135).
Now we are working on the common solution for all our agents for reporting into a single launch.

**Comment by e-fedosser** [comment]
@AmsterGet I already tried this workaround but it didn't help me. It's good looking forward for new solution :) Thank you

**Comment by thomaswinkler** [comment]
@e-fedosser What exactly is not working for you? Can try to help if needed.

**Comment by e-fedosser** [comment]
This issue is out of date. Thank you @thomaswinkler
