### ISSUE TITLE
launchId is not working/recognized

### ISSUE THREAD

**Issue by Gardosen** [reportportal/agent-js-cypress#171]
Hello Everyone,

in the documentation, it is stated that it is possible to forward a launchId to the reporter so it forwards the test results to a specific already created report portal report, based on the launchId.

but it seems this is not working, or has not been implemented at all. i can not find any usage in the codebase of the launchId execpt a lot of appearances of tempLaunchId.

could anyobody help me with this or verify that this is actually a missing feature?

Kind regards
Gardosen

**Comment by AmsterGet** [comment]
Hi @Gardosen !
There was a bug related to this option.
Fixed in [v.5.1.4](https://github.com/reportportal/agent-js-cypress/releases/tag/v5.1.4).
Thanks for pointing this!
