### ISSUE TITLE
The version published in npm registry is ahead of the package.json in the repository

### ISSUE THREAD

**Issue by joseignacioojeda** [reportportal/agent-js-cypress#19]
The last version in https://www.npmjs.com/package/agent-js-cypress is 1.1.3 and in the package.json in the Github repository is 1.1.2. Could you publish and sync the last changes to the npm registry?

**Comment by evjlobanova** [comment]
@ElenaRomanchuk could you please take a look?

**Comment by maromg** [comment]
I'm confused about it too,

are you developing on master and releasing on develop?

**Comment by ElenaRomanchuk** [comment]
We have just released the new version of cypress reporter as a new package `@reportportal/agent-js-cypress`: https://www.npmjs.com/package/@reportportal/agent-js-cypress. The master branch matches to this released version now.
The package https://www.npmjs.com/package/agent-js-cypress is deprecated now.
