### ISSUE TITLE
Current NPM Version 1.1.3 has a high risk vulnerability

### ISSUE THREAD

**Issue by rbdodds-tango** [reportportal/agent-js-cypress#21]
Please remove the `reportportal-client-restler` dependency as it leverages a project that has been dead for 5 years and has security risks.

Dependency of -> agent-js-cypress
Path -> agent-js-cypress > reportportal-client-restler > restler > qs                                                           
More info -> https://npmjs.com/advisories/1469

├─┬ agent-js-cypress@1.1.3
│ └─┬ reportportal-client-restler@1.0.0
│   └─┬ restler@3.4.0
│     └── qs@1.2.0

**Comment by DiscoElevator** [comment]
Hello, @rbdodds-tango 
Thanks for raising this issue. Next release for support RP v5 will have updated dependencies. You can see them in the master branch: [package.json](https://github.com/reportportal/agent-js-cypress/blob/master/package.json)
Please reopen if you have any questions or concerns.
