### ISSUE TITLE
Integration Guidance required for Cypress with ReportPortal

### ISSUE THREAD

**Issue by psubrambe** [reportportal/agent-js-cypress#24]
agent-js-cypress by using the node package we able to integrate with Cypress framework but there is no documentation in ReportPortal.io site

**Comment by ElenaRomanchuk** [comment]
Hi @psubrambe ,
We released the new version of cypress reporter as a new package `@reportportal/agent-js-cypress`: https://www.npmjs.com/package/@reportportal/agent-js-cypress.
It's fully compatible with ReportPortal version 5.* and async API v2 and has some additional features.
The package `agent-js-cypress` is deprecated now.

All information about configuration and usage of the reporter you can find in README in this repository.
Examples of usage you can find here: https://github.com/reportportal/examples-js/tree/master/example-cypress.

If you have any question, feel free to ask us here or join our Slack channel. All contact information you can find in our official website https://reportportal.io/. 
Thank you!
