### ISSUE TITLE
Report Portal Launch when executed in Jenkins not finished

### ISSUE THREAD

**Issue by romerobu** [reportportal/agent-js-cypress#25]
Hi,

My project is configured with cypress client according to the instruction of this repository. 
I've executed it locally integrated with ReportPortal and works OK. However when I execute it on Jenkins (pipeline) even though Jenkins build is success, in Report Portal execution starts fine but never ends. I think it could be some kind of async issue as it seems that report portal is not receiving the end event , but I'm completely lost.

Thanks in advance! 

![image](https://user-images.githubusercontent.com/40232754/78060090-3c726600-738b-11ea-9167-0cf188f08105.png)

**Comment by DzmitryHumianiuk** [comment]
@romerobu RP version and lib version?

**Comment by romerobu** [comment]
"agent-js-cypress": "^1.1.3" and last version of RP @DzmitryHumianiuk

**Comment by ElenaRomanchuk** [comment]
Hi!
We released the new version of cypress reporter as a new package `@reportportal/agent-js-cypress`: https://www.npmjs.com/package/@reportportal/agent-js-cypress. 
It contains some fixes regarding unfinished launches.
Please, let us know if this solves your issue.

**Comment by evjlobanova** [comment]
Closed due to no answer
