### ISSUE TITLE
Field 'startTime' shouldn't be null.

### ISSUE THREAD

**Issue by jadut** [reportportal/agent-js-cypress#33]
Hi All,

I'm trying to use the latest code from the master branch to output my cypress test results into Report Portal. Everything is setup as specified in the readme file, however when I run the tests I get the following error about the start time shouldn't be null.

`Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at \node_modules\reportportal-client\lib\rest.js:27:23
    at processTicksAndRejections (internal/process/task_queues.js:85:5)`

Does anyone have any ideas on why this error is occurring? Do I need to provide a start time myself?

Thanks in advance.

**Comment by ElenaRomanchuk** [comment]
Hi @jadut ,
We released the new version of cypress reporter as a new package `@reportportal/agent-js-cypress`: https://www.npmjs.com/package/@reportportal/agent-js-cypress. You can try it now.
Please, let us know if this solves your issue.
