### ISSUE TITLE
Tests stuck in running state in RP when executed from a docker container

### ISSUE THREAD

**Issue by albadam000** [reportportal/agent-js-cypress#35]
When running cypress tests from within a docker container, the tests are not finishing but getting stuck in a run state in ReportPortal.

The docker image used is : cypress/browsers:node13.6.0-chrome80-ff72
Command to execute tests: 
<entrypoint.sh>
npx cypress run --headless --browser $browser --config-file=cypress/cypress.$env.json --env ***

If the above npx cypress run is the last command in the entrypoint.sh file, the problem occurs, however, if there are further commands after the npx run line (for example an if condition to check exit code), the problem does not occur. (Dockerfile and cypress.json shared in private)

**Comment by ElenaRomanchuk** [comment]
Hi @albadam000 ,
Is this issue still reproducing?

**Comment by albadam000** [comment]
No, issue is not reproducible anymore. Please close. Thank you
