### ISSUE TITLE
Test cases fails to Merge

### ISSUE THREAD

**Issue by vishallanke** [reportportal/agent-js-cypress#36]
Command is `npx cypress run`
I can see that .tmp file gets created. However, I can not see merge launch on report portal.
Inside Cypress.js, I have added logs, these logs are not visible.

`$ npx cypress run

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    4.0.2                                                                              │
  │ Browser:    Electron 78 (headless)                                                             │
  │ Specs:      2 found (actions.spec.js, example.spec.js)                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  actions.spec.js                                                                 (1 of 2)
(node:29316) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:29316) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        14                                                                               │
  │ Passing:      14                                                                               │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     39 seconds                                                                       │
  │ Spec Ran:     actions.spec.js                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────

  Running:  example.spec.js                                                                 (2 of 2)
(node:21340) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(node:21340) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        9                                                                                │
  │ Passing:      6                                                                                │
  │ Failing:      2                                                                                │
  │ Pending:      1                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  4                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     31 seconds                                                                       │
  │ Spec Ran:     example.spec.js                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

  (Screenshots)

  -  D:\Gitlab_Projects\cypress-report-portal\cypress-report-portal-integration\cypre       (114x50)
     ss\screenshots\example.spec.js\Feature  Cypress Report Portal Integration Test -
     - SubFeature  Verify Cypress Examples page -- SubFeature  Verify content Cypress
      example page -- Test  Verify page should contain Commands.png
  -  D:\Gitlab_Projects\cypress-report-portal\cypress-report-portal-integration\cypre     (1280x720)
     ss\screenshots\example.spec.js\Feature  Cypress Report Portal Integration Test -
     - SubFeature  Verify Cypress Examples page -- SubFeature  Verify content Cypress
      example page -- Test  Verify page should contain gfkjdgkjdfgl (failed) (failed)
     .png
  -  D:\Gitlab_Projects\cypress-report-portal\cypress-report-portal-integration\cypre      (272x201)
     ss\screenshots\example.spec.js\Feature  Cypress Report Portal Integration Test -
     - SubFeature  Verify content of Google Dot Com -- Test  Verify contains of googl
     e page (failed).png
  -  D:\Gitlab_Projects\cypress-report-portal\cypress-report-portal-integration\cypre     (1280x720)
     ss\screenshots\example.spec.js\Feature  Cypress Report Portal Integration Test -
     - SubFeature  Verify content of Google Dot Com -- Test  Verify contains of googl
     e page (failed) (failed).png

====================================================================================================

  (Run Finished)

       Spec                                              Tests  Passing  Failing  Pending  Skipped
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ √  actions.spec.js                          00:39       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ×  example.spec.js                          00:31        9        6        2        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ×  1 of 2 failed (50%)                      01:11       23       20        2        1        -
`

{
  "projectId" : "crossVertical",
  "reporter": "index.js",
  "video" : false,
  "reporterOptions": {
      "endpoint": "http://encrypted.amazonaws.com:8080/api/v1",
      "token": "6741d259-6352-3434-4353-059ec805a8ec",
      "launch": "example",
      "project": "cypress_project",
      "description": "END_TO_END VERTICAL",
      "isLaunchMergeRequired": true
  }
}

**Comment by ElenaRomanchuk** [comment]
Hi @vishallanke,
We have just released the new version of cypress reporter as a new package @reportportal/agent-js-cypress: https://www.npmjs.com/package/@reportportal/agent-js-cypress. It has a new possibility of runtime merge launch into single: https://github.com/reportportal/agent-js-cypress#automatically-merge-launches. You can try it now. 
Please, let us know if this solves your issue.

**Comment by vishallanke** [comment]
This issue is Fixed.
Latest RP is hosted on AWS EC2 UBuntu 18.4
Cypress test cases were executed from Git as well as from local machine.
Merge is working successfully.

However, https://github.com/reportportal/agent-js-cypress/issues/37 still exists.
Due to this issue, launches gets merged but test cases wont get uploaded if executed from Git.
