### ISSUE TITLE
When will you post a new version in npm?

### ISSUE THREAD

**Issue by schurakov** [reportportal/agent-js-cypress#44]
Last version was published a year ago: https://www.npmjs.com/package/agent-js-cypress.

Now the code in master branch is different from the plugin code in npm. Thats why instruction for setup custom commands in README.md https://github.com/reportportal/agent-js-cypress/blob/master/README.md#setup-reportportal-custom-commands doesn't work when you install plugin via npm.

**Comment by schurakov** [comment]
Thank you for your answer
I am waiting release. Issue can be closed

**Comment by ElenaRomanchuk** [comment]
Hi @vishallanke,
We have just released the new version of cypress reporter as a new package @reportportal/agent-js-cypress: https://www.npmjs.com/package/@reportportal/agent-js-cypress !
