### ISSUE TITLE
Error on launch - Last update on Master - SIGILL Error

### ISSUE THREAD

**Issue by diogogt** [reportportal/agent-js-cypress#49]
On last update in master I had problem on  launch and dont finished the launch on reportPortal and finish the job and the other test don't execute.

![image](https://user-images.githubusercontent.com/8478768/84507749-b1212500-ac97-11ea-8e85-6afe6c49e12f.png)

**Comment by ElenaRomanchuk** [comment]
Hi @diogogt ,
Is this issue still reproduced with latest released vesrion https://www.npmjs.com/package/@reportportal/agent-js-cypress ?

**Comment by diogogt** [comment]
Hi, I test on last version (5.0.1) and don't have this error again, thank you.
