### ISSUE TITLE
Support for launch attributes

### ISSUE THREAD

**Issue by paulmwhite** [reportportal/agent-js-cypress#57]
I would love to see support for launch based attributes, I couldn't see anything in the documentation, but having looked at the code I have attempted to supply attributes in reporterOptions, as below:

` "reporterOptions": {
    "attributes": [
      { "key": "environment", "value": "dev" },
      { "key": "release", "value": "v0.6.0" }
    ]
  }`

This appears to work for the initial launch, but then I start to see these errors:

`Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'attributes[].value' should not contain only white spaces and shouldn't be empty.] "}
    at /..retracted../node_modules/@reportportal/client-javascript/lib/rest.js:32:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Fail to finish test Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'attributes[].value' should not contain only white spaces and shouldn't be empty.] "}
    at /..retracted../node_modules/@reportportal/client-javascript/lib/rest.js:32:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

Would be really helpful to see this feature working, if possible. Thanks

**Comment by idan-marciano-jfrog** [comment]
@paulmwhite did you find a solution for this problem?
