### ISSUE TITLE
Tests hanging in project with large number of files

### ISSUE THREAD

**Issue by Saoife** [reportportal/agent-js-cypress#73]
Sometimes in a project with a large number of files, the test finishes before the agent can finish searching for any screenshots to attach. The tests in reportportal will hang after that until they time out.

**Comment by tamasmagyar-bridge** [comment]
Duplicate? https://github.com/reportportal/agent-js-cypress/issues/64

**Comment by tamasmagyar** [comment]
Duplicate? https://github.com/reportportal/agent-js-cypress/issues/64

**Comment by ElasticDragonfly** [comment]
> Duplicate? #64

I think that's a different issue, for this one it's the individual tests that don't get completed. Auto-merge doesn't seem to change anything either

**Comment by tamasmagyar** [comment]
> > Duplicate? #64
> 
> I think that's a different issue, for this one it's the individual tests that don't get completed. Auto-merge doesn't seem to change anything either

I think it's kind of a similar issue. The problem is Report Portal closes the "connection" and doesn't wait until the screenshots are uploaded in your case. On #64 it doesn't wait for the auto-merge. Can you check the workaround mentioned in #64 ?

**Comment by AmsterGet** [comment]
Hello @ElasticDragonfly !
Can it be connected with https://github.com/reportportal/agent-js-cypress/issues/76?
This issue already fixed in v5.0.3.

**Comment by AmsterGet** [comment]
Hello @Saoife !
The screenshot mechanism has been completely rewritten and released in version [5.1.2](https://github.com/reportportal/agent-js-cypress/releases/tag/v5.1.2).
Have you tried using it?
Please check your issue with the latest agent version.
Looking forward to your feedback!

**Comment by AmsterGet** [comment]
I'll close this issue.
Feel free to reopen it if your request is still relevant.
