### ISSUE TITLE
How to get logging in report

### ISSUE THREAD

**Issue by fraser-m-hurley-LTK** [reportportal/agent-js-cypress#8]
Hi, I'm looking to implement report portal for a cypress test suite I have. 

From looking through the code I can see there is a sendLog method that is called on the rp:log event being fired. What I don't really understand is how/when that rp:log event is triggered (and therefore what to do within my suite when I want to log something). I also see there is a bunch of event constants in the constants file but it doesn't look like they are used currently? Am I wrong or are they being pulled in by another package?

**Comment by fraser-m-hurley-LTK** [comment]
@avarabyeu are you able to provide in info on this?

**Comment by ElenaRomanchuk** [comment]
@fraser-m-hurley-LTK Are you looking for something like this: https://github.com/reportportal/agent-js-cypress#logging ?

**Comment by fraser-m-hurley-LTK** [comment]
Hi @ElenaRomanchuk, yes this looks like it solves the question I had. Thanks for getting back to me and all your work on the cypress agent recently!!
