### ISSUE TITLE
Getting issue while downloading the "agent-js-cypress" on Windows 64 bit operating system. 

### ISSUE THREAD

**Issue by lakshminagandla** [reportportal/agent-js-cypress#81]
Hi All,

We have downloaded the "agent-js-cypress" with help of Cypress, and while downloading we are getting below warning messages. We believe due to those warning message our messages are not passing to Report portal level.  

Hence could any one please help us to resolve this issue.  

Error messages: 

npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules\@reportportal\agent-js-cypress\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN afta_cypress@1.0.0 No description
npm WARN afta_cypress@1.0.0 No repository field.

Note: We did complete configuration set up as core team provided.

**Comment by LakshmiNagandla** [comment]
Team,  due to this log as well not passing into report portal instance.

**Comment by AmsterGet** [comment]
Hello @lakshminagandla !
I will close this issue due to inactivity.
Feel free to reopen it or create a new one if necessary.
